.TH NLDDCD 8 "22 Oct 2017" "nlddcd"
.SH NAME
nlddcd \- Netlink-based Dynamic DNS Client Daemon
.SH SYNOPSIS
.B nlddcd
.I [OPTIONS]
.SH DESCRIPTION
.B nlddcd
is a Dynamic DNS client. It monitors network interfaces for address changes.
When a change is detected for an interface specified in the configuration
file, the new address is sent to the Dynamic DNS service configured
for that interface, using an HTTP or HTTPS request (see [1]).
.PP
.B nlddcd
does not rely on periodic requests to an external service in order to
detect address changes, but uses the Netlink interface to be notified of changes.
Consequently,
.B nlddcd
does not work behind a NAT and must instead run directly on the router
that contains the interface carrying the "external" IP address(es).
.PP
.B nlddcd
supports IPv4 and IPv6 addresses and will automatically send updates
containing both address types of a configured interface
(however, only global, non-temporary IPv6 addresses will be considered).
.SH OPTIONS
.TP
.BR -h ", " --help
Show help message and exit.
.TP
.BR -v ", " --version
Show version info and exit.
.TP
\fB\-c\fR \fIFILE\fR, \fB--config\fR \fIFILE\fR
Read configuration from FILE instead of the default
configuration file.
.SH FILES
.TP
.I /etc/nlddcd.conf
Default configuration file.
.SH BUGS
Please send bug reports to
.UR christof@efkemann.net
Christof Efkemann
.UE .
.SH SEE ALSO
.IP 1. 4
Dynamic DNS update protocol description
.RS 4
\%https://help.dyn.com/remote-access-api/perform-update/
.RE
