.TH NLDDCD 8 "30 Sep 2017" "nlddcd"
.SH NAME
nlddcd \- Netlink-based Dynamic DNS Client Daemon
.SH SYNOPSIS
.B nlddcd
.I [OPTIONS]
.SH DESCRIPTION
.B nlddcd
updates dynamic ...
.SH OPTIONS
.TP
.BR -h ", " --help
Show help message and exit.
.TP
.BR -v ", " --version
Show version info and exit.
.SH FILES
.TP
.I /etc/nlddcd.conf
Default config file.
.SH BUGS
Please send bug reports to
.UR christof@efkemann.net
Christof Efkemann
.UE .
